name: Install Dependencies

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Use a supported version, like 3.8
          architecture: x64  # Specify the architecture

      - name: Create virtual environment
        run: python -m venv venv
        shell: bash

      - name: Activate virtual environment
        run: source venv/bin/activate
        shell: bash

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install streamlit nltk
        shell: bash

      - name: Print installed packages
        run: pip list
        shell: bash
